"""Reconstruct recognized text into .docx and .md files.

Inputs:
    - List of recognized regions with position + text + confidence + source.

Outputs:
    - Markdown (intermediate, easy to review)
    - .docx (final deliverable) with paragraphs + tables preserved
"""
from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from docx import Document
from docx.shared import Pt

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
from src.layout import Region, RegionType  # noqa: E402


@dataclass
class RecognizedRegion:
    region: Region
    text: str
    confidence: float
    source: str  # "vietocr" or "grok"


def _sorted_reading_order(regions: Iterable[RecognizedRegion]) -> list[RecognizedRegion]:
    return sorted(regions, key=lambda r: (r.region.y1, r.region.x1))


def _reconstruct_table_grid(table_regions: list[RecognizedRegion]) -> list[list[str]]:
    """Reconstruct a 2D grid from text-regions that spatially overlap the table.

    For MVP heuristics: bucket child text regions by horizontal/vertical alignment.
    """
    if not table_regions:
        return []
    # Use first table region as the area; collect all text in same y/x hierarchy
    # Simpler MVP: just join rows top-to-bottom, left-to-right.
    rows = sorted(table_regions, key=lambda r: (r.region.y1, r.region.x1))
    # Group by Y (rows)
    grid: list[list[str]] = []
    current_row: list[RecognizedRegion] = []
    last_y = -1000
    for r in rows:
        if r.region.y1 - last_y > 30:
            if current_row:
                grid.append(current_row)
            current_row = [r]
        else:
            current_row.append(r)
        last_y = r.region.y1
    if current_row:
        grid.append(current_row)
    return [[r.text for r in sorted(row, key=lambda x: x.region.x1)] for row in grid]


def to_markdown(
    recognized: list[RecognizedRegion],
    table_subregions: dict[int, list[RecognizedRegion]] | None = None,
) -> str:
    """Convert recognized regions to markdown.

    `table_subregions` maps table region index -> list of its text sub-regions.
    """
    table_subs = table_subregions or {}
    out_lines: list[str] = []
    table_idx = 0

    for rec in _sorted_reading_order(recognized):
        if rec.region.type == RegionType.TEXT:
            out_lines.append(rec.text)
        elif rec.region.type == RegionType.TABLE:
            # Heading
            out_lines.append(f"\n[TABLE {table_idx}]\n")
            grid = _reconstruct_table_grid(table_subs.get(table_idx, []))
            if grid:
                ncols = max(len(row) for row in grid)
                header = grid[0] + [""] * (ncols - len(grid[0]))
                out_lines.append("| " + " | ".join(header) + " |")
                out_lines.append("| " + " | ".join(["---"] * ncols) + " |")
                for row in grid[1:]:
                    row = row + [""] * (ncols - len(row))
                    out_lines.append("| " + " | ".join(row) + " |")
            else:
                out_lines.append("(empty table)")
            out_lines.append("")
            table_idx += 1
    return "\n".join(out_lines)


def to_docx(
    recognized: list[RecognizedRegion],
    table_subregions: dict[int, list[RecognizedRegion]] | None,
    output_path: str | Path,
    title: str = "Vietnamese OCR Output",
) -> None:
    """Write a .docx file with paragraphs and tables preserved."""
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(12)

    h = doc.add_heading(title, level=1)
    doc.add_paragraph("Generated by Vietnamese OCR Pipeline (VietOCR + Grok 4.5 fallback).")

    _, _, _, _ = None, None, None, None  # silence linter
    table_subs = table_subregions or {}
    table_idx = 0

    for rec in _sorted_reading_order(recognized):
        if rec.region.type == RegionType.TEXT:
            doc.add_paragraph(rec.text)
        elif rec.region.type == RegionType.TABLE:
            doc.add_paragraph().add_run(f"[Table {table_idx}]").bold = True
            grid = _reconstruct_table_grid(table_subs.get(table_idx, []))
            if grid:
                ncols = max(len(row) for row in grid)
                tbl = doc.add_table(rows=len(grid), cols=ncols)
                tbl.style = "Light Grid Accent 1"
                for i, row in enumerate(grid):
                    for j, cell_text in enumerate(row):
                        if j < ncols:
                            tbl.cell(i, j).text = cell_text
            table_idx += 1

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output_path))


def save_markdown(content: str, output_path: str | Path) -> None:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def main() -> int:
    import argparse
    import json
    parser = argparse.ArgumentParser(description="Reconstruct OCR result into .docx/.md")
    parser.add_argument("--input", required=True,
                        help="JSON file with list of recognized regions")
    parser.add_argument("--output", required=True, help="Output .docx path")
    parser.add_argument("--md", default=None, help="Optional .md path")
    args = parser.parse_args()

    data = json.loads(Path(args.input).read_text(encoding="utf-8"))
    recognized: list[RecognizedRegion] = []
    for d in data:
        region = Region(
            x1=d["x1"], y1=d["y1"], x2=d["x2"], y2=d["y2"],
            type=RegionType(d.get("type", "text")),
        )
        recognized.append(RecognizedRegion(
            region=region, text=d["text"], confidence=d.get("confidence", 0.0),
            source=d.get("source", "vietocr"),
        ))
    to_docx(recognized, table_subregions={}, output_path=args.output)
    if args.md:
        save_markdown(to_markdown(recognized), args.md)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
